title: PhD Annual Symposium 2026
description: PhD Annual Symposium hosted by HEC Montr√©al
baseurl: ""
url: "https://www.phdsymposium2026.ca"

collections:
  sessions:
    output: true
    permalink: /en/sessions/:name.html