title: PhD Annual Symposium 2026
description: PhD Annual Symposium hosted by HEC Montr√©al
baseurl: ""
url: "https://www.phdsymposium2026.ca"

collections:
  sessions_en:
    output: true
    permalink: /en/sessions/:name.html

  sessions:
    output: true
    permalink: /sessions/:name.html

  workshops_en:
    output: true
    permalink: /en/ateliers/:name.html

  workshops:
    output: true
    permalink: /ateliers/:name.html

  roundtables_en:
    output: true
    permalink: /en/tablesrondes/:name.html

  roundtables:
    output: true
    permalink: /tablesrondes/:name.html

future: true